parse piuparts.conf instead of hardcoding those two values taken from there

diff --git a/home/piupartsm/bin/detect_archive_issues b/home/piupartsm/bin/detect_archive_issues
--- a/home/piupartsm/bin/detect_archive_issues
+++ b/home/piupartsm/bin/detect_archive_issues
@@ -16,19 +16,29 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 
-MASTER=/org/piuparts.debian.org/master
-DISTROS="sid squeeze"
+#
+# parse config file
+#
+
+TEMPFILE=`mktemp`
+egrep "(^sections|^master-directory)" /etc/piuparts/piuparts.conf| sed -e "s# ##g" -e "s#sections#SECTIONS#" -e "s#master-directory#MASTER#" > $TEMPFILE
+source $TEMPFILE
+rm $TEMPFILE
+if [ -z $MASTER ] || [ -z $SECTIONS ] ; then
+	echo "sections and/or master-directory not set in /etc/piuparts/piuparts.conf, exiting."
+	exit 1
+fi
 
 #
 # detect packages which are/were untestable due to archive issue and mark them as such
 #
 
 LOGS=`mktemp`
-for distro in $DISTROS ; do 
-	rgrep -l "E: Broken packages" $MASTER/$distro/fail 2>/dev/null >> $LOGS
+for SECTION in $SECTIONS ; do 
+	rgrep -l "E: Broken packages" $MASTER/$SECTION/fail 2>/dev/null >> $LOGS
         if [ -s $LOGS ] ; then 
-          for package_log in $(grep $distro $LOGS) ; do 
-		mv $package_log $MASTER/$distro/untestable/
+          for package_log in $(grep $SECTION $LOGS) ; do 
+		mv $package_log $MASTER/$SECTION/untestable/
 	  done
         fi
 done
@@ -36,7 +46,7 @@ if [ -s $LOGS ] ; then
 	echo "Broken packages detected!"
 	echo "(By grep'ing for 'E: Broken packages' in failed logs.)"
 	echo 
-	echo 'The following packages have been moved to $distro/untestable and will be'
+	echo 'The following packages have been moved to $section/untestable and will be'
 	echo "tested again in 7 days."
 	echo
         echo "Broken packages are usually a temporarily problem in the archive and are"
@@ -45,7 +55,7 @@ if [ -s $LOGS ] ; then
 	echo "If is is always the same package failing, it's likely to be an issue in the"
 	echo "package."
 	echo
-	cat $LOGS | sed -e "s#/org/piuparts.debian.org/master/#http://piuparts.debian.org/#g" -e "s#/fail#/untestable#g"
+	cat $LOGS | sed -e "s#$MASTER#http://piuparts.debian.org/#g" -e "s#/fail#/untestable#g"
 	echo
 fi
 rm $LOGS
