detect_{piuparts,network}_issues: report found issues
Signed-off-by: Andreas Beckmann <anbe@debian.org>
Signed-off-by: Holger Levsen <holger@layer-acht.org>

diff --git a/master-bin/detect_piuparts_issues.in b/master-bin/detect_piuparts_issues.in
--- a/master-bin/detect_piuparts_issues.in
+++ b/master-bin/detect_piuparts_issues.in
@@ -29,47 +29,63 @@ STARTDATE=$(date -u +%s)
 # detect piuparts problems
 #
 
+newline="
+"
+tab="	"
+PATTERN=
+DISPLAY_PATTERN=
+
+add_pattern()
+{
+	PATTERN="${PATTERN:+${PATTERN}|}($1)"
+	DISPLAY_PATTERN="${DISPLAY_PATTERN:+${DISPLAY_PATTERN}${newline}}${tab}$1"
+}
+
+add_pattern 'PIUPARTS OUTPUT INCOMPLETE'
+add_pattern "WARNING: History of available packages does not match - reference chroot may be outdated"
+add_pattern "tar( \(child\))?: .*.tar.gz: Cannot open: No such file or directory"
+add_pattern "tar: Error is not recoverable: exiting now"
+add_pattern "gzip: stdin: invalid compressed data--crc error"
+add_pattern "ERROR:.*:Temporary directory is not a directory"
+add_pattern "E: Sub-process Popen returned an error code \(2\)"
+add_pattern "chroot: failed to run command '.*': Permission denied"
+add_pattern "ERROR: Command failed \(status=-7\): .* 'apt-cache'"
+add_pattern 'update-binfmts: warning: unable to close /proc/sys/fs/binfmt_misc/register: Invalid argument'
+add_pattern 'userdel: user .* is currently logged in'
+# Disk space issues.
+add_pattern "No space left on device"
+add_pattern "E: You don't have enough free space in /var/cache/apt/archives/"
+add_pattern "E: Failed to write temporary StateFile /var/lib/apt/extended_states.tmp"
+add_pattern "tar: .*: Wrote only .* of .* bytes"
+add_pattern "passwd: Authentication token manipulation error"
+add_pattern "(chfn|groupadd|useradd): (cannot lock|failure while writing changes to) /etc/(group|gshadow|passwd|shadow|subuid)"
+add_pattern "(groupadd|useradd): (unable to lock|cannot rewrite) (group|password) file"
+# Database server issues.
+add_pattern 'invoke-rc.d: initscript mysql, action "(start|restart)" failed.'
+add_pattern 'invoke-rc.d: initscript postgresql, action "start" failed.'
+add_pattern 'The PostgreSQL server failed to start.'
+add_pattern 'No database found online on port 5432'
+add_pattern 'unable to connect to postgresql server'
+add_pattern 'Failed to connect to postgres.'
+add_pattern 'PG::ConnectionBad: could not connect to server'
+add_pattern 'psql: FATAL:  password authentication failed for user'
+add_pattern 'createuser: could not connect to database postgres: could not connect to server: No such file or directory'
+add_pattern 'Non-default port in /etc/postgresql/.*/main/postgresql.conf'
+add_pattern 'Firebird .* server already running.'
+# These are python errors from piuparts itself. Python errors from maintainer
+# scripts etc. would be indented by 2 spaces, so don't match here.
+add_pattern "^RuntimeError: maximum recursion depth exceeded while calling a Python object"
+add_pattern "^Traceback"
+add_pattern "^OSError:"
+add_pattern "^IndentationError:"
+add_pattern "^SyntaxError:"
+
 FILE=`mktemp`
 for SECTION in $SECTIONS ; do
 	test -d $MASTER/$SECTION || continue
 	for subdir in fail bugged affected ; do
 		test -d $MASTER/$SECTION/$subdir || continue
-		rgrep -l 'PIUPARTS OUTPUT INCOMPLETE' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l "WARNING: History of available packages does not match - reference chroot may be outdated" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -E "tar( \(child\))?: .*.tar.gz: Cannot open: No such file or directory" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "tar: Error is not recoverable: exiting now" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "tar: .*: Wrote only .* of .* bytes" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "gzip: stdin: invalid compressed data--crc error" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "ERROR:.*:Temporary directory is not a directory" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -i -e "No space left on device" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "E: You don't have enough free space in /var/cache/apt/archives/" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "E: Failed to write temporary StateFile /var/lib/apt/extended_states.tmp" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "passwd: Authentication token manipulation error" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -E "(chfn|groupadd|useradd): (cannot lock|failure while writing changes to) /etc/(group|gshadow|passwd|shadow|subuid)" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -E "(groupadd|useradd): (unable to lock|cannot rewrite) (group|password) file" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "E: Sub-process Popen returned an error code (2)" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "chroot: failed to run command '.*': Permission denied" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "ERROR: Command failed (status=-7): .* 'apt-cache'" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "^RuntimeError: maximum recursion depth exceeded while calling a Python object" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "^Traceback" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "^OSError:" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "^IndentationError:" $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e "^SyntaxError:" $MASTER/$SECTION/$subdir >> $FILE
-		# Python errors from maintainer scripts etc. would be indented by 2 spaces, so don't match here.
-		rgrep -l -e 'update-binfmts: warning: unable to close /proc/sys/fs/binfmt_misc/register: Invalid argument' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'userdel: user .* is currently logged in' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -i -E 'invoke-rc.d: initscript mysql, action "(start|restart)" failed.' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -i -e 'invoke-rc.d: initscript postgresql, action "start" failed.' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'The PostgreSQL server failed to start.' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -i -e 'FATAL:  could not create shared memory segment: No space left on device' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'No database found online on port 5432' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'unable to connect to postgresql server' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'Failed to connect to postgres.' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'PG::ConnectionBad: could not connect to server' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'psql: FATAL:  password authentication failed for user' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'createuser: could not connect to database postgres: could not connect to server: No such file or directory' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'Non-default port in /etc/postgresql/.*/main/postgresql.conf' $MASTER/$SECTION/$subdir >> $FILE
-		rgrep -l -e 'Firebird .* server already running.' $MASTER/$SECTION/$subdir >> $FILE
+		grep -r -l -E --include '*.log' "$PATTERN" $MASTER/$SECTION/$subdir >> $FILE
 		find $MASTER/$SECTION/$subdir -name '*.log' -size 0 >> $FILE
 	done
 done
@@ -78,18 +94,26 @@ if [ -s $FILE ] ; then
 	RUNTIME=$(date -u -d "0 $FINALDATE seconds - $STARTDATE seconds" +%T)
 	echo "Runtime: $RUNTIME"
 	echo
-	echo "piuparts problem detected!"
-	echo "(By grep'ing for)"
-	grep rgrep $0 | grep -v "grep rgrep" | cut -d "\$" -f1
+	echo "piuparts problems detected!"
+	echo "(By grep'ing for"
+	echo "$DISPLAY_PATTERN"
 	echo "in failed logs.)"
 	echo
 	echo "Please review the following logfiles/packages."
 	echo "If it is always the same package failing, it's likely to be an issue in the"
 	echo "package."
 	echo
-		sort -u $FILE | xargs rm -v
+	echo "The following logfiles have been deleted:"
 	echo
 	echo "----------------------------------------------------------------------"
+	echo
+	for log in $(sort -u $FILE)
+	do
+		echo "$log"
+		test -s "$log" || echo "${tab}Empty logfile."
+		grep -E "$PATTERN" "$log" | perl -e 'print grep !$seen{$_}++, <>;' | head -n 10 | sed "s/^/${tab}/"
+		rm -f "$log"
+	done
 	echo
 fi
 rm $FILE
