post_du_exceptions: buster: remove empty unowned /etc/dbus-1/{system.d/,}
systemd no longer ships /etc/dbus-1/system.d/* in buster, but dpkg does
not clean up the now empty unowned directories after the upgrade from
stretch to buster

cleanup will happen if another package ships /etc/dbus-1/system.d/*
in buster and gets purged in buster, causing discrepancies with the
reference chroot:

  ERROR: FAIL: After purging files have disappeared:
    /etc/dbus-1/	 owned by: dbus
    /etc/dbus-1/system.d/	 owned by: dbus

Signed-off-by: Andreas Beckmann <anbe@debian.org>
Signed-off-by: Holger Levsen <holger@layer-acht.org>

diff --git a/custom-scripts/scripts/post_distupgrade_exceptions b/custom-scripts/scripts/post_distupgrade_exceptions
--- a/custom-scripts/scripts/post_distupgrade_exceptions
+++ b/custom-scripts/scripts/post_distupgrade_exceptions
@@ -81,3 +81,16 @@ if [ "$PIUPARTS_DISTRIBUTION" = "stretch" ]; then
 	done
 
 fi
+
+if [ "$PIUPARTS_DISTRIBUTION" = "buster" ]; then
+
+	# dpkg does not properly clean up directories getting empty and no longer shipped
+	for dir in /etc/dbus-1/system.d /etc/dbus-1
+	do
+		if [ -d "$dir" ]; then
+			rmdir --ignore-fail-on-non-empty "$dir"
+			test -d "$dir" || echo "removed empty directory '$dir'"
+		fi
+	done
+
+fi
