fix upgrading to squeeze-backports
Signed-off-by: Andreas Beckmann <anbe@debian.org>
Signed-off-by: Holger Levsen <holger@layer-acht.org>

diff --git a/custom-scripts/scripts/pre_distupgrade_allow_unauthenticated b/custom-scripts/scripts/pre_distupgrade_allow_unauthenticated
--- a/custom-scripts/scripts/pre_distupgrade_allow_unauthenticated
+++ b/custom-scripts/scripts/pre_distupgrade_allow_unauthenticated
@@ -14,11 +14,6 @@ if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "wheezy" ]; then
 	rm -fv /etc/apt/apt.conf.d/unauthenticated-squeeze
 fi
 
-if [ -e /etc/apt/apt.conf.d/unauthenticated-squeeze ]; then
-	echo "FAIL: /etc/apt/apt.conf.d/unauthenticated-squeeze exists"
-	exit 1
-fi
-
 if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "squeeze" ]; then
 	echo "Creating /etc/apt/apt.conf.d/unauthenticated-squeeze ..."
 	# apt/lenny does not like comments ...
@@ -26,4 +21,9 @@ if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "squeeze" ]; then
 APT::Get::AllowUnauthenticated "true";
 Acquire::Check-Valid-Until "false";
 EOF
+elif [ "$PIUPARTS_DISTRIBUTION_NEXT" = "squeeze-backports" ]; then
+	:
+elif [ -e /etc/apt/apt.conf.d/unauthenticated-squeeze ]; then
+	echo "FAIL: /etc/apt/apt.conf.d/unauthenticated-squeeze exists"
+	exit 1
 fi
