add distupgrade exception for dnscache-run
dnscache-run breaks DNS inside the chroot
abort early on distupgrades i.e. before this produces
network errors caught by detect_network_errors

Signed-off-by: Andreas Beckmann <anbe@debian.org>

diff --git a/custom-scripts/scripts/pre_distupgrade_exceptions b/custom-scripts/scripts/pre_distupgrade_exceptions
--- a/custom-scripts/scripts/pre_distupgrade_exceptions
+++ b/custom-scripts/scripts/pre_distupgrade_exceptions
@@ -65,3 +65,16 @@ if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "jessie" ]; then
 	esac
 
 fi
+
+if [ "$PIUPARTS_DISTRIBUTION_NEXT" = "experimental" ]; then
+
+	case ${PIUPARTS_OBJECTS} in
+		dnscache-run=1:1.05-9~exp2)
+			#664848: breaks dns resolution in chroot if installed in a chroot
+			log_debug
+			echo "*** ABORT - Installation broke DNS in chroot ***"
+			exit 1
+			;;
+	esac
+
+fi
